version: 0.0
os: linux
files:
  - source: /
    destination: /opt/myapp
permissions:
  - object: /opt/myapp
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 30
      runas: root
  ValidateService:
    - location: validate_service.sh
      timeout: 30
      runas: root