version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/spring_boot
    overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: clear.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: fix_privileges.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: server_start.sh
      timeout: 300
      runas: root