version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/spring_boot
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root