version: 0.2
phases:
  # install:
  #   runtime-versions:
  #     java: corretto17  # Adjust Java version if needed
  #   commands:
  #     - echo Entered install phase...
  #     - mvn clean

  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 794132765434.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - echo Entered build phase...
      - echo Build started on `date`
      - mvn clean package -DskipTests=true
      - ls target/

      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - docker images
      - echo Build completed on `date`
      - echo Pushing Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      
      - echo Creating JSON file for AWS CodeDeploy...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_REPO_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.m2/**/*'  # Cache Maven dependencies
